### ISSUE TITLE
Is there any starter that use this plugin?

### ISSUE THREAD

**Issue by TaylanTatli** [johackim/gatsby-remark-obsidian#1]
I'm using digital garden starter, and it lacks custom title for bracket links. I want to use this plugin with it or Andy starter, but couldn't manage to do that. I have no knowledge in Gatsby, all I know is 11ty, Jekyll, Hugo etc. Is there any step-by-step guide or starter?

**Comment by johackim** [comment]
Hello @TaylanTatli,

I added examples : https://github.com/johackim/gatsby-remark-obsidian/tree/master/examples

Don't hesitate if you have questions ;)
